### ISSUE TITLE
WIP: Sylius Cashback (Rewards) Plugin

### ISSUE THREAD

**Issue by gabiudrescu** [friendsofsylius/SyliusGoose#12]
The plugin repository is here: https://github.com/Snake-Tn/SyliusRewardPlugin

@Snake-Tn is working on it. feel free to give a helping hand. 

I suggest to include in the list once the author decides to mark it as functional / beta.

**Comment by bitbager** [comment]
Nice! I will create another section for WIP plugins and add them to the README file later.

**Comment by bitbager** [comment]
Closed in 3f85da8768537d472cfa8fb94b838f2c26c6595f 🎉

**Comment by gabiudrescu** [comment]
to be honest, I was rather thinking to use issues from GitHub to keep the state of the development of such plugins while their WIP and when done, close the issue with a MR. 

rather than have a list of WIP in the main readme.md.

**Comment by bitbager** [comment]
Wouldn't it be too complicated for now?

**Comment by stefandoorn** [comment]
This way it's also easy for people to see which plugins for sure need help :)

**Comment by bitbager** [comment]
Yes, for sure, but for now we are having two WIP plugins on the list and forcing people to open an issue and integrate everything, at least for now is not necessary. I'd say that after having 10/15 WIP plugins, we can consider it.

**Comment by gabiudrescu** [comment]
fair enough.
