### ISSUE TITLE
exchange rate import plugin

### ISSUE THREAD

**Issue by lsmith77** [friendsofsylius/SyliusGoose#20]
during the Sylius training at Liip, we created a plugin that makes it easy to update exchange rates from external sources. I propose we add it to FriendsOfSylius:
https://github.com/liip/SyliusExchangeRatesPlugin

namespace is already prepared .. I can give someone admin rights on https://github.com/liip/SyliusExchangeRatesPlugin so that one of the org owners can do the move.

**Comment by bitbager** [comment]
Could you provide a PR?

**Comment by lsmith77** [comment]
uhm .. what do you mean PR? to what repo should I send a PR? basically I am asking to move the repo itself from the liip org to the FriendsOfSylius org

**Comment by bitbager** [comment]
Ough, sorry, I read it quickly and thought you want it to be mentioned in the Goose file 😄. I will give you the access to the organization in a minute. Please, close this issue once you're done 🙂

**Comment by lsmith77** [comment]
done https://github.com/FriendsOfSylius/SyliusExchangeRatesPlugin

**Comment by bitbager** [comment]
Could you also mention it in the README? 🎉

**Comment by lsmith77** [comment]
https://github.com/FriendsOfSylius/SyliusGoose/pull/21

**Comment by bitbager** [comment]
Thanks!
