### ISSUE TITLE
Sylake - Sylius & Akeneo integration

### ISSUE THREAD

**Issue by gabiudrescu** [friendsofsylius/SyliusGoose#7]
Should we mention the packages from https://github.com/Sylake here, too?

**Comment by bitbager** [comment]
Hmm, the question is - do we consider Sylius as friends of themselves? If so, I would put all the Sylius plugins into the README file.

**Comment by gabiudrescu** [comment]
well, I see this a bit different: this repo is created by friends of Sylius (the platform) for the users (everybody - incl. people who consider themselves friends of the Sylius platform).

not including Sylake repos in this list means, in my opinion, less exposure for these amazing plugins. 

hence my proposal to incl. them too.

**Comment by bitbager** [comment]
I agree. Would you like to open a PR?

**Comment by bitbager** [comment]
Closed in c1890eff303cb00f965c359150952014441fb9ae 🙂
